service: uk-covid19-service

package:
  individually: true

custom:
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  web-bff:
    handler: packages/server/src/handler.default
    events:
      - http:
          path: dashboard
          method: get
      - http:
          path: geo-data
          method: get
