service: uk-covid19-service

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    ALLOWED_ORIGIN: ${self:custom.envs.allowedOrigin}

custom:
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    httpPort: 4000
  envs: ${file(./environments.js):environments.${self:custom.stage}}
  s3Sync:
    - bucketName: ${self:custom.envs.webBucketName}
      localDir: packages/web/build

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-s3-sync

functions:
  web-bff:
    handler: packages/server/src/handler.default
    events:
      - http:
          path: dashboard
          method: get
          cors:
            origins:
              - '${self:custom.envs.allowedOrigin}'
      - http:
          path: geo-data
          method: get
          cors:
            origins:
              - '${self:custom.envs.allowedOrigin}'
resources:
  Resources:
    WebBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.envs.webBucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
